package tcc.kt

import java.io.File
import java.nio.ByteOrder
import java.util.concurrent.TimeUnit

/** Kotlin port of conftest.c: the host probe and C-header-to-string converter. */
object Conftest {
    private val platformMacros = linkedMapOf(
        "__i386__" to "TCC_TARGET_I386",
        "__x86_64__" to "TCC_TARGET_X86_64",
        "_WIN32" to "TCC_TARGET_PE",
        "__arm__" to "TCC_TARGET_ARM",
        "__ARM_EABI__" to "TCC_ARM_EABI",
        "__aarch64__" to "TCC_TARGET_ARM64",
        "__riscv" to "TCC_TARGET_RISCV64",
        "__APPLE__" to "TCC_TARGET_MACHO",
        "__FreeBSD__" to "TARGETOS_FreeBSD",
        "__FreeBSD_kernel__" to "TARGETOS_FreeBSD_kernel",
        "__OpenBSD__" to "TARGETOS_OpenBSD",
        "__NetBSD__" to "TARGETOS_NetBSD",
        "__linux__" to "TARGETOS_Linux",
        "__ANDROID__" to "TARGETOS_ANDROID",
        "__SIZEOF_POINTER__" to "PTR_SIZE",
        "__SIZEOF_LONG__" to "LONG_SIZE",
    )

    @JvmStatic
    fun main(args: Array<String>) {
        kotlin.system.exitProcess(run(args))
    }

    fun run(args: Array<String>): Int {
        if (args.size == 2) {
            return try {
                File(args[1]).writeText(convertCHeaderToStrings(File(args[0]).readText()), Charsets.UTF_8)
                0
            } catch (_: Exception) {
                System.err.println("c2str: file error")
                1
            }
        }
        if (args.size != 1 || args[0].isEmpty()) return 0
        val probe = HostProbe()
        val result = when (args[0][0]) {
            'b' -> if (ByteOrder.nativeOrder() == ByteOrder.LITTLE_ENDIAN) "no" else "yes"
            'm' -> probe.compilerMinor()
            'v' -> probe.compilerVersion()
            't' -> probe.triplet()
            'c' -> probe.compilerName()
            else -> ""
        }
        if (result.isNotEmpty()) println(result)
        return 0
    }

    /** Recreates the line folding, macro replacement, comment pass, and string escaping in -DC2STR mode. */
    fun convertCHeaderToStrings(source: String): String {
        val output = StringBuilder()
        var blockComment = false
        var commentCount = 0

        for (line in joinedLines(source)) {
            val trimmed = line.trimEnd { it.code <= 32 }
            var first = 0
            while (first < trimmed.length && isSpace(trimmed[first])) first++

            if (blockComment || (first < trimmed.length && trimmed[first] == '/' &&
                    first + 1 < trimmed.length && (trimmed[first + 1] == '*' || trimmed[first + 1] == '/'))) {
                if (!blockComment && trimmed.getOrNull(first + 1) == '*') blockComment = true
                output.append(trimmed)
                if (++commentCount == 1) output.append(" (converted, do not edit this file)")
                output.append('\n')
                if (!blockComment) continue
                if (trimmed.endsWith("*/")) blockComment = false
                continue
            }

            val text = trimmed.substring(first)
            if (first < 4) {
                output.append(replacePlatformMacros(text)).append('\n')
            } else {
                val (quoted, comment) = quoteCodeLine(text)
                output.append("    \"").append(quoted).append("\\n\"")
                if (comment != null) output.append(comment)
                output.append('\n')
            }
        }
        return output.toString()
    }

    private fun joinedLines(source: String): List<String> {
        val result = mutableListOf<String>()
        var pending = StringBuilder()
        val physicalLines = source.split('\n').let { if (source.endsWith('\n')) it.dropLast(1) else it }
        for (raw in physicalLines) {
            val line = raw.trimEnd { it.code <= 32 }
            if (line.endsWith('\\')) pending.append(line.dropLast(1)).append(' ')
            else {
                pending.append(line)
                result.add(pending.toString())
                pending = StringBuilder()
            }
        }
        if (pending.isNotEmpty()) result.add(pending.toString())
        return result
    }

    private fun replacePlatformMacros(source: String): String {
        val result = StringBuilder()
        var cursor = 0
        while (cursor < source.length) {
            val replacement = platformMacros.entries.firstOrNull { (macro, _) -> source.startsWith(macro, cursor) }
            if (replacement == null) result.append(source[cursor++])
            else {
                result.append(replacement.value)
                cursor += replacement.key.length
            }
        }
        return result.toString()
    }

    private fun quoteCodeLine(source: String): Pair<String, String?> {
        val out = StringBuilder()
        var cursor = 0
        var pendingSpace = false
        var parenDepth = 0
        var insertedSpaces = 0
        var commentStart: Int? = null

        while (cursor < source.length) {
            var ch = source[cursor]
            if (isSpace(ch)) {
                pendingSpace = true
                cursor++
                continue
            }
            if (ch == '/' && source.getOrNull(cursor + 1) in listOf('/', '*')) {
                commentStart = cursor
                break
            }

            val prev = out.lastOrNull()
            val tokenNeedsSpace = pendingSpace && prev != null &&
                ((isIdentifier(prev) && isIdentifier(ch)) ||
                    (out.startsWith("#d") && insertedSpaces < 2 && parenDepth == 0))
            if (tokenNeedsSpace) {
                out.append(' ')
                insertedSpaces++
            }
            pendingSpace = false
            if (ch == '(') parenDepth++
            if (ch == ')') parenDepth--
            if (ch == '\\' || ch == '"') out.append('\\')
            out.append(ch)
            cursor++
        }

        return out.toString() to commentStart?.let { source.substring(it) }
    }

    private fun isSpace(ch: Char): Boolean = ch.code <= 32
    private fun isIdentifier(ch: Char): Boolean = ch in 'a'..'z' || ch in 'A'..'Z' || ch in '0'..'9' || ch == '_'

    private class HostProbe {
        private val command = (System.getenv("CC") ?: "cc").split(Regex("\\s+")).filter { it.isNotBlank() }
        private val versionOutput by lazy { runCompiler("--version") }
        private val versionNumbers by lazy {
            val full = runCompiler("-dumpfullversion").lineSequence().firstOrNull().orEmpty()
            val reported = Regex("(\\d+)\\.(\\d+)").find(full)?.groupValues
                ?: Regex("(?:version\\s+)?(\\d+)\\.(\\d+)", RegexOption.IGNORE_CASE)
                    .find(versionOutput)?.groupValues
            (reported?.getOrNull(1) ?: "0") to (reported?.getOrNull(2) ?: "0")
        }

        fun compilerName(): String = when {
            versionOutput.contains("clang", ignoreCase = true) -> "clang"
            versionOutput.contains("tiny c", ignoreCase = true) || command.firstOrNull()?.contains("tcc") == true -> "tcc"
            versionOutput.contains("microsoft", ignoreCase = true) -> "msvc"
            versionOutput.contains("gcc", ignoreCase = true) || versionOutput.contains("gnu", ignoreCase = true) -> "gcc"
            else -> "unknown"
        }

        fun compilerVersion(): String = versionNumbers.first

        fun compilerMinor(): String = versionNumbers.second

        fun triplet(): String {
            runCompiler("-dumpmachine").lineSequence().firstOrNull()?.trim()?.takeIf { it.isNotEmpty() }?.let { return it }
            val arch = when (System.getProperty("os.arch").lowercase()) {
                "x86", "i386", "i486", "i586", "i686" -> "i386"
                "amd64", "x86_64" -> "x86_64"
                "arm", "arm32" -> "arm"
                "aarch64", "arm64" -> "aarch64"
                "riscv64" -> "riscv64"
                else -> "unknown"
            }
            val osName = System.getProperty("os.name").lowercase()
            val os = when {
                osName.contains("linux") -> "linux"
                osName.contains("freebsd") -> "kfreebsd"
                osName.contains("netbsd") -> "netbsd"
                osName.contains("openbsd") -> "openbsd"
                osName.contains("windows") -> "win32"
                osName.contains("mac") || osName.contains("darwin") -> "darwin"
                else -> "unknown"
            }
            return if (os == "win32") "$arch-$os" else "$arch-$os-gnu"
        }

        private fun runCompiler(vararg arguments: String): String {
            if (command.isEmpty()) return ""
            return try {
                val process = ProcessBuilder(command + arguments).redirectErrorStream(true).start()
                if (!process.waitFor(5, TimeUnit.SECONDS)) {
                    process.destroyForcibly()
                    return ""
                }
                process.inputStream.bufferedReader().use { it.readText() }
            } catch (_: Exception) {
                ""
            }
        }
    }
}
